void main(
	float4 in_pos,
	float4 in_color,
	float2 in_tex0,
	out float4 gl_Position : POSITION,
	out float4 v_color : COLOR,
	out float2 v_tex0 : TEXCOORD0,
	out float v_fog : FOG,
	uniform float4 u_xform
)
{
	gl_Position = in_pos;
	gl_Position.xy = gl_Position.xy * u_xform.xy + u_xform.zw;
	v_fog = DoFog(gl_Position.z);
	gl_Position.xyz *= gl_Position.w;
	v_color = in_color;
	v_tex0 = in_tex0;
}