void main(
	float3 in_pos,
	float4 in_color,
	float2 in_tex0,
	uniform float4 u_fogData,
	uniform float4x4 u_proj,
	uniform float4x4 u_world,
	uniform float4x4 u_view,
	out float4 gl_Position : POSITION,
	out float4 v_color : COLOR0,
	out float2 v_tex0 : TEXCOORD0,
	out float v_fog : FOG
)
{
	float4 V = mul(float4(in_pos, 1.0), u_world);
	gl_Position = mul(mul(V, u_view), u_proj);
	v_color = in_color;
	v_tex0 = in_tex0;
	v_fog = DoFog(gl_Position.w, u_fogData);
}